{"failedCount":1,"prefixedPath":"src\/test\/java\/teachers\/patch\/teacher-patch.feature","packageQualifiedName":"src.test.java.teachers.patch.teacher-patch","loopIndex":-1,"relativePath":"src\/test\/java\/teachers\/patch\/teacher-patch.feature","scenarioResults":[{"sectionIndex":0,"stepResults":[{"result":{"nanos":1500891300,"errorMessage":"status code was: 500, expected: 200, response time in milliseconds: 785, url: https:\/\/funcoeback-dev-ceqh.3.us-1.fl0.io\/users\/token\/, response: \nTraceback (most recent call last):\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1969, in _exec_single_context\n    self.dialect.do_execute(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/default.py\", line 922, in do_execute\n    cursor.execute(statement, parameters)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/cursors.py\", line 153, in execute\n    result = self._query(query)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/cursors.py\", line 322, in _query\n    conn.query(q)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 558, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 822, in _read_query_result\n    result.read()\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 1200, in read\n    first_packet = self.connection._read_packet()\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 739, in _read_packet\n    packet_header = self._read_bytes(4)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 795, in _read_bytes\n    raise err.OperationalError(\npymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/middleware\/errors.py\", line 164, in __call__\n    await self.app(scope, receive, _send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/middleware\/cors.py\", line 83, in __call__\n    await self.app(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/middleware\/exceptions.py\", line 62, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 64, in wrapped_app\n    raise exc\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 53, in wrapped_app\n    await app(scope, receive, sender)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 762, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 782, in app\n    await route.handle(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 297, in handle\n    await self.app(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 77, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 64, in wrapped_app\n    raise exc\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 53, in wrapped_app\n    await app(scope, receive, sender)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 72, in app\n    response = await func(request)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/fastapi\/routing.py\", line 299, in app\n    raise e\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/fastapi\/routing.py\", line 294, in app\n    raw_response = await run_endpoint_function(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/fastapi\/routing.py\", line 193, in run_endpoint_function\n    return await run_in_threadpool(dependant.call, **values)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/concurrency.py\", line 40, in run_in_threadpool\n    return await anyio.to_thread.run_sync(func, *args)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/anyio\/to_thread.py\", line 56, in run_sync\n    return await get_async_backend().run_sync_in_worker_thread(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/anyio\/_backends\/_asyncio.py\", line 2134, in run_sync_in_worker_thread\n    return await future\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/anyio\/_backends\/_asyncio.py\", line 851, in run\n    result = context.run(func, *args)\n  File \"\/workspace\/app\/routes\/user.py\", line 19, in get_token\n    if validate_user(user):\n  File \"\/workspace\/app\/func\/user.py\", line 22, in validate_user\n    id_user = get_uuid_user(data.user)\n  File \"\/workspace\/app\/func\/user.py\", line 37, in get_uuid_user\n    r1=db.query(user_model).where(user_model.user==user).one()\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/orm\/query.py\", line 2798, in one\n    return self._iter().one()  # type: ignore\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/orm\/query.py\", line 2847, in _iter\n    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/orm\/session.py\", line 2308, in execute\n    return self._execute_internal(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/orm\/session.py\", line 2190, in _execute_internal\n    result: Result[Any] = compile_state_cls.orm_execute_statement(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/orm\/context.py\", line 293, in orm_execute_statement\n    result = conn.execute(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1416, in execute\n    return meth(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/sql\/elements.py\", line 517, in _execute_on_connection\n    return connection._execute_clauseelement(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1639, in _execute_clauseelement\n    ret = self._execute_context(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1848, in _execute_context\n    return self._exec_single_context(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1988, in _exec_single_context\n    self._handle_dbapi_exception(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 2344, in _handle_dbapi_exception\n    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1969, in _exec_single_context\n    self.dialect.do_execute(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/default.py\", line 922, in do_execute\n    cursor.execute(statement, parameters)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/cursors.py\", line 153, in execute\n    result = self._query(query)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/cursors.py\", line 322, in _query\n    conn.query(q)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 558, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 822, in _read_query_result\n    result.read()\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 1200, in read\n    first_packet = self.connection._read_packet()\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 739, in _read_packet\n    packet_header = self._read_bytes(4)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 795, in _read_bytes\n    raise err.OperationalError(\nsqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')\n[SQL: SELECT users.uuid_user AS users_uuid_user, users.user AS users_user, users.password AS users_password, users.rol_uuid AS users_rol_uuid, users.is_active AS users_is_active, users.last_connection AS users_last_connection, users.created_at AS users_created_at, users.updated_at AS users_updated_at \nFROM users \nWHERE users.user = %(user_1)s]\n[parameters: {'user_1': 'ruben1'}]\n(Background on this error at: https:\/\/sqlalche.me\/e\/20\/e3q8)\n\nsrc\/test\/java\/teachers\/patch\/..\/..\/user\/token\/users-token-post.feature:9\nsrc\/test\/java\/teachers\/patch\/teacher-patch.feature:4","millis":1500.8913,"status":"failed"},"step":{"background":true,"line":4,"prefix":"*","index":0,"text":"call read(\"..\/..\/user\/token\/users-token-post.feature@token\")"},"stepLog":"22:15:40.790 src\/test\/java\/teachers\/patch\/teacher-patch.feature:4\n* call read(\"..\/..\/user\/token\/users-token-post.feature@token\")\nstatus code was: 500, expected: 200, response time in milliseconds: 785, url: https:\/\/funcoeback-dev-ceqh.3.us-1.fl0.io\/users\/token\/, response: \nTraceback (most recent call last):\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1969, in _exec_single_context\n    self.dialect.do_execute(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/default.py\", line 922, in do_execute\n    cursor.execute(statement, parameters)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/cursors.py\", line 153, in execute\n    result = self._query(query)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/cursors.py\", line 322, in _query\n    conn.query(q)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 558, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 822, in _read_query_result\n    result.read()\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 1200, in read\n    first_packet = self.connection._read_packet()\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 739, in _read_packet\n    packet_header = self._read_bytes(4)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 795, in _read_bytes\n    raise err.OperationalError(\npymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/middleware\/errors.py\", line 164, in __call__\n    await self.app(scope, receive, _send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/middleware\/cors.py\", line 83, in __call__\n    await self.app(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/middleware\/exceptions.py\", line 62, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 64, in wrapped_app\n    raise exc\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 53, in wrapped_app\n    await app(scope, receive, sender)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 762, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 782, in app\n    await route.handle(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 297, in handle\n    await self.app(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 77, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 64, in wrapped_app\n    raise exc\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 53, in wrapped_app\n    await app(scope, receive, sender)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 72, in app\n    response = await func(request)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/fastapi\/routing.py\", line 299, in app\n    raise e\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/fastapi\/routing.py\", line 294, in app\n    raw_response = await run_endpoint_function(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/fastapi\/routing.py\", line 193, in run_endpoint_function\n    return await run_in_threadpool(dependant.call, **values)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/concurrency.py\", line 40, in run_in_threadpool\n    return await anyio.to_thread.run_sync(func, *args)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/anyio\/to_thread.py\", line 56, in run_sync\n    return await get_async_backend().run_sync_in_worker_thread(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/anyio\/_backends\/_asyncio.py\", line 2134, in run_sync_in_worker_thread\n    return await future\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/anyio\/_backends\/_asyncio.py\", line 851, in run\n    result = context.run(func, *args)\n  File \"\/workspace\/app\/routes\/user.py\", line 19, in get_token\n    if validate_user(user):\n  File \"\/workspace\/app\/func\/user.py\", line 22, in validate_user\n    id_user = get_uuid_user(data.user)\n  File \"\/workspace\/app\/func\/user.py\", line 37, in get_uuid_user\n    r1=db.query(user_model).where(user_model.user==user).one()\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/orm\/query.py\", line 2798, in one\n    return self._iter().one()  # type: ignore\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/orm\/query.py\", line 2847, in _iter\n    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/orm\/session.py\", line 2308, in execute\n    return self._execute_internal(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/orm\/session.py\", line 2190, in _execute_internal\n    result: Result[Any] = compile_state_cls.orm_execute_statement(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/orm\/context.py\", line 293, in orm_execute_statement\n    result = conn.execute(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1416, in execute\n    return meth(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/sql\/elements.py\", line 517, in _execute_on_connection\n    return connection._execute_clauseelement(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1639, in _execute_clauseelement\n    ret = self._execute_context(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1848, in _execute_context\n    return self._exec_single_context(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1988, in _exec_single_context\n    self._handle_dbapi_exception(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 2344, in _handle_dbapi_exception\n    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1969, in _exec_single_context\n    self.dialect.do_execute(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/default.py\", line 922, in do_execute\n    cursor.execute(statement, parameters)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/cursors.py\", line 153, in execute\n    result = self._query(query)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/cursors.py\", line 322, in _query\n    conn.query(q)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 558, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 822, in _read_query_result\n    result.read()\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 1200, in read\n    first_packet = self.connection._read_packet()\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 739, in _read_packet\n    packet_header = self._read_bytes(4)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 795, in _read_bytes\n    raise err.OperationalError(\nsqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')\n[SQL: SELECT users.uuid_user AS users_uuid_user, users.user AS users_user, users.password AS users_password, users.rol_uuid AS users_rol_uuid, users.is_active AS users_is_active, users.last_connection AS users_last_connection, users.created_at AS users_created_at, users.updated_at AS users_updated_at \nFROM users \nWHERE users.user = %(user_1)s]\n[parameters: {'user_1': 'ruben1'}]\n(Background on this error at: https:\/\/sqlalche.me\/e\/20\/e3q8)\n\nsrc\/test\/java\/teachers\/patch\/..\/..\/user\/token\/users-token-post.feature:9\nsrc\/test\/java\/teachers\/patch\/teacher-patch.feature:4\n","callResults":[{"failedCount":1,"prefixedPath":"src\/test\/java\/teachers\/patch\/..\/..\/user\/token\/users-token-post.feature","packageQualifiedName":"src.test.java.teachers.patch.user.token.users-token-post","loopIndex":-1,"relativePath":"src\/test\/java\/teachers\/patch\/..\/..\/user\/token\/users-token-post.feature","scenarioResults":[{"sectionIndex":0,"stepResults":[{"result":{"nanos":2576100,"millis":2.5761,"status":"passed"},"step":{"line":6,"prefix":"Given","index":0,"text":"url \"https:\/\/funcoeback-dev-ceqh.3.us-1.fl0.io\/users\/token\/\""}},{"result":{"nanos":56946499,"millis":56.946499,"status":"passed"},"step":{"line":7,"prefix":"And","index":1,"text":"request {\"user\": \"ruben1\", \"password\": \"ruben123\"}"}},{"result":{"nanos":1242346401,"millis":1242.346401,"status":"passed"},"step":{"line":8,"prefix":"When","index":2,"text":"method post"},"stepLog":"22:15:39.994 request:\n1 > POST https:\/\/funcoeback-dev-ceqh.3.us-1.fl0.io\/users\/token\/\n1 > Content-Type: application\/json; charset=UTF-8\n1 > Content-Length: 39\n1 > Host: funcoeback-dev-ceqh.3.us-1.fl0.io\n1 > Connection: Keep-Alive\n1 > User-Agent: Apache-HttpClient\/4.5.13 (Java\/21.0.2)\n1 > Accept-Encoding: gzip,deflate\n{\"user\":\"ruben1\",\"password\":\"ruben123\"}\n\n22:15:40.781 response time in milliseconds: 785\n1 < 500\n1 < date: Thu, 21 Mar 2024 03:15:40 GMT\n1 < server: envoy\n1 < content-length: 9580\n1 < content-type: text\/plain; charset=utf-8\n1 < x-envoy-upstream-service-time: 8\nTraceback (most recent call last):\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1969, in _exec_single_context\n    self.dialect.do_execute(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/default.py\", line 922, in do_execute\n    cursor.execute(statement, parameters)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/cursors.py\", line 153, in execute\n    result = self._query(query)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/cursors.py\", line 322, in _query\n    conn.query(q)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 558, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 822, in _read_query_result\n    result.read()\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 1200, in read\n    first_packet = self.connection._read_packet()\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 739, in _read_packet\n    packet_header = self._read_bytes(4)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 795, in _read_bytes\n    raise err.OperationalError(\npymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/middleware\/errors.py\", line 164, in __call__\n    await self.app(scope, receive, _send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/middleware\/cors.py\", line 83, in __call__\n    await self.app(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/middleware\/exceptions.py\", line 62, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 64, in wrapped_app\n    raise exc\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 53, in wrapped_app\n    await app(scope, receive, sender)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 762, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 782, in app\n    await route.handle(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 297, in handle\n    await self.app(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 77, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 64, in wrapped_app\n    raise exc\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 53, in wrapped_app\n    await app(scope, receive, sender)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 72, in app\n    response = await func(request)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/fastapi\/routing.py\", line 299, in app\n    raise e\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/fastapi\/routing.py\", line 294, in app\n    raw_response = await run_endpoint_function(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/fastapi\/routing.py\", line 193, in run_endpoint_function\n    return await run_in_threadpool(dependant.call, **values)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/concurrency.py\", line 40, in run_in_threadpool\n    return await anyio.to_thread.run_sync(func, *args)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/anyio\/to_thread.py\", line 56, in run_sync\n    return await get_async_backend().run_sync_in_worker_thread(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/anyio\/_backends\/_asyncio.py\", line 2134, in run_sync_in_worker_thread\n    return await future\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/anyio\/_backends\/_asyncio.py\", line 851, in run\n    result = context.run(func, *args)\n  File \"\/workspace\/app\/routes\/user.py\", line 19, in get_token\n    if validate_user(user):\n  File \"\/workspace\/app\/func\/user.py\", line 22, in validate_user\n    id_user = get_uuid_user(data.user)\n  File \"\/workspace\/app\/func\/user.py\", line 37, in get_uuid_user\n    r1=db.query(user_model).where(user_model.user==user).one()\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/orm\/query.py\", line 2798, in one\n    return self._iter().one()  # type: ignore\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/orm\/query.py\", line 2847, in _iter\n    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/orm\/session.py\", line 2308, in execute\n    return self._execute_internal(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/orm\/session.py\", line 2190, in _execute_internal\n    result: Result[Any] = compile_state_cls.orm_execute_statement(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/orm\/context.py\", line 293, in orm_execute_statement\n    result = conn.execute(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1416, in execute\n    return meth(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/sql\/elements.py\", line 517, in _execute_on_connection\n    return connection._execute_clauseelement(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1639, in _execute_clauseelement\n    ret = self._execute_context(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1848, in _execute_context\n    return self._exec_single_context(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1988, in _exec_single_context\n    self._handle_dbapi_exception(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 2344, in _handle_dbapi_exception\n    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1969, in _exec_single_context\n    self.dialect.do_execute(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/default.py\", line 922, in do_execute\n    cursor.execute(statement, parameters)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/cursors.py\", line 153, in execute\n    result = self._query(query)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/cursors.py\", line 322, in _query\n    conn.query(q)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 558, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 822, in _read_query_result\n    result.read()\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 1200, in read\n    first_packet = self.connection._read_packet()\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 739, in _read_packet\n    packet_header = self._read_bytes(4)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 795, in _read_bytes\n    raise err.OperationalError(\nsqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')\n[SQL: SELECT users.uuid_user AS users_uuid_user, users.user AS users_user, users.password AS users_password, users.rol_uuid AS users_rol_uuid, users.is_active AS users_is_active, users.last_connection AS users_last_connection, users.created_at AS users_created_at, users.updated_at AS users_updated_at \nFROM users \nWHERE users.user = %(user_1)s]\n[parameters: {'user_1': 'ruben1'}]\n(Background on this error at: https:\/\/sqlalche.me\/e\/20\/e3q8)\n\n\n"},{"result":{"nanos":4099300,"errorMessage":"status code was: 500, expected: 200, response time in milliseconds: 785, url: https:\/\/funcoeback-dev-ceqh.3.us-1.fl0.io\/users\/token\/, response: \nTraceback (most recent call last):\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1969, in _exec_single_context\n    self.dialect.do_execute(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/default.py\", line 922, in do_execute\n    cursor.execute(statement, parameters)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/cursors.py\", line 153, in execute\n    result = self._query(query)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/cursors.py\", line 322, in _query\n    conn.query(q)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 558, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 822, in _read_query_result\n    result.read()\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 1200, in read\n    first_packet = self.connection._read_packet()\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 739, in _read_packet\n    packet_header = self._read_bytes(4)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 795, in _read_bytes\n    raise err.OperationalError(\npymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/middleware\/errors.py\", line 164, in __call__\n    await self.app(scope, receive, _send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/middleware\/cors.py\", line 83, in __call__\n    await self.app(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/middleware\/exceptions.py\", line 62, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 64, in wrapped_app\n    raise exc\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 53, in wrapped_app\n    await app(scope, receive, sender)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 762, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 782, in app\n    await route.handle(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 297, in handle\n    await self.app(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 77, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 64, in wrapped_app\n    raise exc\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 53, in wrapped_app\n    await app(scope, receive, sender)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 72, in app\n    response = await func(request)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/fastapi\/routing.py\", line 299, in app\n    raise e\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/fastapi\/routing.py\", line 294, in app\n    raw_response = await run_endpoint_function(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/fastapi\/routing.py\", line 193, in run_endpoint_function\n    return await run_in_threadpool(dependant.call, **values)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/concurrency.py\", line 40, in run_in_threadpool\n    return await anyio.to_thread.run_sync(func, *args)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/anyio\/to_thread.py\", line 56, in run_sync\n    return await get_async_backend().run_sync_in_worker_thread(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/anyio\/_backends\/_asyncio.py\", line 2134, in run_sync_in_worker_thread\n    return await future\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/anyio\/_backends\/_asyncio.py\", line 851, in run\n    result = context.run(func, *args)\n  File \"\/workspace\/app\/routes\/user.py\", line 19, in get_token\n    if validate_user(user):\n  File \"\/workspace\/app\/func\/user.py\", line 22, in validate_user\n    id_user = get_uuid_user(data.user)\n  File \"\/workspace\/app\/func\/user.py\", line 37, in get_uuid_user\n    r1=db.query(user_model).where(user_model.user==user).one()\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/orm\/query.py\", line 2798, in one\n    return self._iter().one()  # type: ignore\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/orm\/query.py\", line 2847, in _iter\n    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/orm\/session.py\", line 2308, in execute\n    return self._execute_internal(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/orm\/session.py\", line 2190, in _execute_internal\n    result: Result[Any] = compile_state_cls.orm_execute_statement(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/orm\/context.py\", line 293, in orm_execute_statement\n    result = conn.execute(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1416, in execute\n    return meth(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/sql\/elements.py\", line 517, in _execute_on_connection\n    return connection._execute_clauseelement(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1639, in _execute_clauseelement\n    ret = self._execute_context(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1848, in _execute_context\n    return self._exec_single_context(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1988, in _exec_single_context\n    self._handle_dbapi_exception(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 2344, in _handle_dbapi_exception\n    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1969, in _exec_single_context\n    self.dialect.do_execute(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/default.py\", line 922, in do_execute\n    cursor.execute(statement, parameters)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/cursors.py\", line 153, in execute\n    result = self._query(query)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/cursors.py\", line 322, in _query\n    conn.query(q)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 558, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 822, in _read_query_result\n    result.read()\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 1200, in read\n    first_packet = self.connection._read_packet()\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 739, in _read_packet\n    packet_header = self._read_bytes(4)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 795, in _read_bytes\n    raise err.OperationalError(\nsqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')\n[SQL: SELECT users.uuid_user AS users_uuid_user, users.user AS users_user, users.password AS users_password, users.rol_uuid AS users_rol_uuid, users.is_active AS users_is_active, users.last_connection AS users_last_connection, users.created_at AS users_created_at, users.updated_at AS users_updated_at \nFROM users \nWHERE users.user = %(user_1)s]\n[parameters: {'user_1': 'ruben1'}]\n(Background on this error at: https:\/\/sqlalche.me\/e\/20\/e3q8)\n\nsrc\/test\/java\/teachers\/patch\/..\/..\/user\/token\/users-token-post.feature:9","millis":4.0993,"status":"failed"},"step":{"line":9,"prefix":"Then","index":3,"text":"status 200"},"stepLog":"22:15:40.788 src\/test\/java\/teachers\/patch\/..\/..\/user\/token\/users-token-post.feature:9\nThen status 200\nstatus code was: 500, expected: 200, response time in milliseconds: 785, url: https:\/\/funcoeback-dev-ceqh.3.us-1.fl0.io\/users\/token\/, response: \nTraceback (most recent call last):\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1969, in _exec_single_context\n    self.dialect.do_execute(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/default.py\", line 922, in do_execute\n    cursor.execute(statement, parameters)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/cursors.py\", line 153, in execute\n    result = self._query(query)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/cursors.py\", line 322, in _query\n    conn.query(q)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 558, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 822, in _read_query_result\n    result.read()\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 1200, in read\n    first_packet = self.connection._read_packet()\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 739, in _read_packet\n    packet_header = self._read_bytes(4)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 795, in _read_bytes\n    raise err.OperationalError(\npymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/middleware\/errors.py\", line 164, in __call__\n    await self.app(scope, receive, _send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/middleware\/cors.py\", line 83, in __call__\n    await self.app(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/middleware\/exceptions.py\", line 62, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 64, in wrapped_app\n    raise exc\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 53, in wrapped_app\n    await app(scope, receive, sender)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 762, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 782, in app\n    await route.handle(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 297, in handle\n    await self.app(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 77, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 64, in wrapped_app\n    raise exc\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 53, in wrapped_app\n    await app(scope, receive, sender)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 72, in app\n    response = await func(request)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/fastapi\/routing.py\", line 299, in app\n    raise e\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/fastapi\/routing.py\", line 294, in app\n    raw_response = await run_endpoint_function(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/fastapi\/routing.py\", line 193, in run_endpoint_function\n    return await run_in_threadpool(dependant.call, **values)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/concurrency.py\", line 40, in run_in_threadpool\n    return await anyio.to_thread.run_sync(func, *args)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/anyio\/to_thread.py\", line 56, in run_sync\n    return await get_async_backend().run_sync_in_worker_thread(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/anyio\/_backends\/_asyncio.py\", line 2134, in run_sync_in_worker_thread\n    return await future\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/anyio\/_backends\/_asyncio.py\", line 851, in run\n    result = context.run(func, *args)\n  File \"\/workspace\/app\/routes\/user.py\", line 19, in get_token\n    if validate_user(user):\n  File \"\/workspace\/app\/func\/user.py\", line 22, in validate_user\n    id_user = get_uuid_user(data.user)\n  File \"\/workspace\/app\/func\/user.py\", line 37, in get_uuid_user\n    r1=db.query(user_model).where(user_model.user==user).one()\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/orm\/query.py\", line 2798, in one\n    return self._iter().one()  # type: ignore\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/orm\/query.py\", line 2847, in _iter\n    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/orm\/session.py\", line 2308, in execute\n    return self._execute_internal(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/orm\/session.py\", line 2190, in _execute_internal\n    result: Result[Any] = compile_state_cls.orm_execute_statement(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/orm\/context.py\", line 293, in orm_execute_statement\n    result = conn.execute(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1416, in execute\n    return meth(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/sql\/elements.py\", line 517, in _execute_on_connection\n    return connection._execute_clauseelement(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1639, in _execute_clauseelement\n    ret = self._execute_context(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1848, in _execute_context\n    return self._exec_single_context(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1988, in _exec_single_context\n    self._handle_dbapi_exception(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 2344, in _handle_dbapi_exception\n    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1969, in _exec_single_context\n    self.dialect.do_execute(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/default.py\", line 922, in do_execute\n    cursor.execute(statement, parameters)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/cursors.py\", line 153, in execute\n    result = self._query(query)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/cursors.py\", line 322, in _query\n    conn.query(q)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 558, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 822, in _read_query_result\n    result.read()\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 1200, in read\n    first_packet = self.connection._read_packet()\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 739, in _read_packet\n    packet_header = self._read_bytes(4)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 795, in _read_bytes\n    raise err.OperationalError(\nsqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')\n[SQL: SELECT users.uuid_user AS users_uuid_user, users.user AS users_user, users.password AS users_password, users.rol_uuid AS users_rol_uuid, users.is_active AS users_is_active, users.last_connection AS users_last_connection, users.created_at AS users_created_at, users.updated_at AS users_updated_at \nFROM users \nWHERE users.user = %(user_1)s]\n[parameters: {'user_1': 'ruben1'}]\n(Background on this error at: https:\/\/sqlalche.me\/e\/20\/e3q8)\n\nsrc\/test\/java\/teachers\/patch\/..\/..\/user\/token\/users-token-post.feature:9\n"},{"result":{"nanos":0,"millis":0.0,"status":"skipped"},"step":{"line":10,"prefix":"*","index":4,"text":"def token = $.access_token"}}],"line":5,"description":"","durationMillis":1305.9683,"failed":true,"error":"status code was: 500, expected: 200, response time in milliseconds: 785, url: https:\/\/funcoeback-dev-ceqh.3.us-1.fl0.io\/users\/token\/, response: \nTraceback (most recent call last):\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1969, in _exec_single_context\n    self.dialect.do_execute(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/default.py\", line 922, in do_execute\n    cursor.execute(statement, parameters)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/cursors.py\", line 153, in execute\n    result = self._query(query)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/cursors.py\", line 322, in _query\n    conn.query(q)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 558, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 822, in _read_query_result\n    result.read()\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 1200, in read\n    first_packet = self.connection._read_packet()\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 739, in _read_packet\n    packet_header = self._read_bytes(4)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 795, in _read_bytes\n    raise err.OperationalError(\npymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/middleware\/errors.py\", line 164, in __call__\n    await self.app(scope, receive, _send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/middleware\/cors.py\", line 83, in __call__\n    await self.app(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/middleware\/exceptions.py\", line 62, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 64, in wrapped_app\n    raise exc\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 53, in wrapped_app\n    await app(scope, receive, sender)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 762, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 782, in app\n    await route.handle(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 297, in handle\n    await self.app(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 77, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 64, in wrapped_app\n    raise exc\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 53, in wrapped_app\n    await app(scope, receive, sender)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 72, in app\n    response = await func(request)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/fastapi\/routing.py\", line 299, in app\n    raise e\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/fastapi\/routing.py\", line 294, in app\n    raw_response = await run_endpoint_function(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/fastapi\/routing.py\", line 193, in run_endpoint_function\n    return await run_in_threadpool(dependant.call, **values)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/concurrency.py\", line 40, in run_in_threadpool\n    return await anyio.to_thread.run_sync(func, *args)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/anyio\/to_thread.py\", line 56, in run_sync\n    return await get_async_backend().run_sync_in_worker_thread(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/anyio\/_backends\/_asyncio.py\", line 2134, in run_sync_in_worker_thread\n    return await future\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/anyio\/_backends\/_asyncio.py\", line 851, in run\n    result = context.run(func, *args)\n  File \"\/workspace\/app\/routes\/user.py\", line 19, in get_token\n    if validate_user(user):\n  File \"\/workspace\/app\/func\/user.py\", line 22, in validate_user\n    id_user = get_uuid_user(data.user)\n  File \"\/workspace\/app\/func\/user.py\", line 37, in get_uuid_user\n    r1=db.query(user_model).where(user_model.user==user).one()\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/orm\/query.py\", line 2798, in one\n    return self._iter().one()  # type: ignore\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/orm\/query.py\", line 2847, in _iter\n    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/orm\/session.py\", line 2308, in execute\n    return self._execute_internal(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/orm\/session.py\", line 2190, in _execute_internal\n    result: Result[Any] = compile_state_cls.orm_execute_statement(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/orm\/context.py\", line 293, in orm_execute_statement\n    result = conn.execute(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1416, in execute\n    return meth(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/sql\/elements.py\", line 517, in _execute_on_connection\n    return connection._execute_clauseelement(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1639, in _execute_clauseelement\n    ret = self._execute_context(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1848, in _execute_context\n    return self._exec_single_context(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1988, in _exec_single_context\n    self._handle_dbapi_exception(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 2344, in _handle_dbapi_exception\n    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1969, in _exec_single_context\n    self.dialect.do_execute(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/default.py\", line 922, in do_execute\n    cursor.execute(statement, parameters)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/cursors.py\", line 153, in execute\n    result = self._query(query)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/cursors.py\", line 322, in _query\n    conn.query(q)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 558, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 822, in _read_query_result\n    result.read()\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 1200, in read\n    first_packet = self.connection._read_packet()\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 739, in _read_packet\n    packet_header = self._read_bytes(4)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 795, in _read_bytes\n    raise err.OperationalError(\nsqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')\n[SQL: SELECT users.uuid_user AS users_uuid_user, users.user AS users_user, users.password AS users_password, users.rol_uuid AS users_rol_uuid, users.is_active AS users_is_active, users.last_connection AS users_last_connection, users.created_at AS users_created_at, users.updated_at AS users_updated_at \nFROM users \nWHERE users.user = %(user_1)s]\n[parameters: {'user_1': 'ruben1'}]\n(Background on this error at: https:\/\/sqlalche.me\/e\/20\/e3q8)\n\nsrc\/test\/java\/teachers\/patch\/..\/..\/user\/token\/users-token-post.feature:9","tags":["token"],"executorName":"main","name":"Post a token","startTime":1710990939479,"refId":"[1:5]","endTime":1710990940788,"exampleIndex":-1}],"callDepth":1,"name":"JWT Token Feature","description":"","resultDate":"2024-03-20 10:15:46 p.\u202Fm.","durationMillis":1305.9683,"passedCount":0}]},{"result":{"nanos":0,"millis":0.0,"status":"skipped"},"step":{"background":true,"line":5,"prefix":"*","index":1,"text":"header Authorization = \"Bearer \" + token"}},{"result":{"nanos":0,"millis":0.0,"status":"skipped"},"step":{"background":true,"line":6,"prefix":"*","index":2,"text":"print token"}},{"result":{"nanos":0,"millis":0.0,"status":"skipped"},"step":{"background":true,"line":7,"prefix":"*","index":3,"text":"call read(\"..\/post\/teacher-post.feature@createteachers\")"}},{"result":{"nanos":0,"millis":0.0,"status":"skipped"},"step":{"line":12,"prefix":"Given","index":0,"text":"url 'https:\/\/funcoeback-dev-ceqh.3.us-1.fl0.io\/teachers\/uuid_teacher?uuid=' + teacherId"}},{"result":{"nanos":0,"millis":0.0,"status":"skipped"},"step":{"line":13,"prefix":"*","index":1,"text":"print teacherId"}},{"result":{"nanos":0,"millis":0.0,"status":"skipped"},"step":{"line":14,"prefix":"And","index":2,"text":"request {\"first_name\": '#(randomname)',  \"last_name\": '#(randomlastname)', \"phone\": '#(randomphone)',  \"program_uuid\": \"50ae87d2-09de-4a87-aeca-a4236d9a602b\"}"}},{"result":{"nanos":0,"millis":0.0,"status":"skipped"},"step":{"line":15,"prefix":"When","index":3,"text":"method patch"}},{"result":{"nanos":0,"millis":0.0,"status":"skipped"},"step":{"line":16,"prefix":"Then","index":4,"text":"status 200"}},{"result":{"nanos":0,"millis":0.0,"status":"skipped"},"step":{"line":17,"prefix":"And","index":5,"text":"print \"El Registro Se Actualizo De Forma Exitosa \" + teacherId"}}],"line":11,"description":"","durationMillis":1500.8913,"failed":true,"error":"status code was: 500, expected: 200, response time in milliseconds: 785, url: https:\/\/funcoeback-dev-ceqh.3.us-1.fl0.io\/users\/token\/, response: \nTraceback (most recent call last):\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1969, in _exec_single_context\n    self.dialect.do_execute(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/default.py\", line 922, in do_execute\n    cursor.execute(statement, parameters)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/cursors.py\", line 153, in execute\n    result = self._query(query)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/cursors.py\", line 322, in _query\n    conn.query(q)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 558, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 822, in _read_query_result\n    result.read()\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 1200, in read\n    first_packet = self.connection._read_packet()\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 739, in _read_packet\n    packet_header = self._read_bytes(4)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 795, in _read_bytes\n    raise err.OperationalError(\npymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/middleware\/errors.py\", line 164, in __call__\n    await self.app(scope, receive, _send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/middleware\/cors.py\", line 83, in __call__\n    await self.app(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/middleware\/exceptions.py\", line 62, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 64, in wrapped_app\n    raise exc\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 53, in wrapped_app\n    await app(scope, receive, sender)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 762, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 782, in app\n    await route.handle(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 297, in handle\n    await self.app(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 77, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 64, in wrapped_app\n    raise exc\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 53, in wrapped_app\n    await app(scope, receive, sender)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 72, in app\n    response = await func(request)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/fastapi\/routing.py\", line 299, in app\n    raise e\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/fastapi\/routing.py\", line 294, in app\n    raw_response = await run_endpoint_function(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/fastapi\/routing.py\", line 193, in run_endpoint_function\n    return await run_in_threadpool(dependant.call, **values)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/concurrency.py\", line 40, in run_in_threadpool\n    return await anyio.to_thread.run_sync(func, *args)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/anyio\/to_thread.py\", line 56, in run_sync\n    return await get_async_backend().run_sync_in_worker_thread(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/anyio\/_backends\/_asyncio.py\", line 2134, in run_sync_in_worker_thread\n    return await future\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/anyio\/_backends\/_asyncio.py\", line 851, in run\n    result = context.run(func, *args)\n  File \"\/workspace\/app\/routes\/user.py\", line 19, in get_token\n    if validate_user(user):\n  File \"\/workspace\/app\/func\/user.py\", line 22, in validate_user\n    id_user = get_uuid_user(data.user)\n  File \"\/workspace\/app\/func\/user.py\", line 37, in get_uuid_user\n    r1=db.query(user_model).where(user_model.user==user).one()\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/orm\/query.py\", line 2798, in one\n    return self._iter().one()  # type: ignore\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/orm\/query.py\", line 2847, in _iter\n    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/orm\/session.py\", line 2308, in execute\n    return self._execute_internal(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/orm\/session.py\", line 2190, in _execute_internal\n    result: Result[Any] = compile_state_cls.orm_execute_statement(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/orm\/context.py\", line 293, in orm_execute_statement\n    result = conn.execute(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1416, in execute\n    return meth(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/sql\/elements.py\", line 517, in _execute_on_connection\n    return connection._execute_clauseelement(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1639, in _execute_clauseelement\n    ret = self._execute_context(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1848, in _execute_context\n    return self._exec_single_context(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1988, in _exec_single_context\n    self._handle_dbapi_exception(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 2344, in _handle_dbapi_exception\n    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/base.py\", line 1969, in _exec_single_context\n    self.dialect.do_execute(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/sqlalchemy\/engine\/default.py\", line 922, in do_execute\n    cursor.execute(statement, parameters)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/cursors.py\", line 153, in execute\n    result = self._query(query)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/cursors.py\", line 322, in _query\n    conn.query(q)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 558, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 822, in _read_query_result\n    result.read()\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 1200, in read\n    first_packet = self.connection._read_packet()\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 739, in _read_packet\n    packet_header = self._read_bytes(4)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/pymysql\/connections.py\", line 795, in _read_bytes\n    raise err.OperationalError(\nsqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')\n[SQL: SELECT users.uuid_user AS users_uuid_user, users.user AS users_user, users.password AS users_password, users.rol_uuid AS users_rol_uuid, users.is_active AS users_is_active, users.last_connection AS users_last_connection, users.created_at AS users_created_at, users.updated_at AS users_updated_at \nFROM users \nWHERE users.user = %(user_1)s]\n[parameters: {'user_1': 'ruben1'}]\n(Background on this error at: https:\/\/sqlalche.me\/e\/20\/e3q8)\n\nsrc\/test\/java\/teachers\/patch\/..\/..\/user\/token\/users-token-post.feature:9\nsrc\/test\/java\/teachers\/patch\/teacher-patch.feature:4","tags":["updateteachertotal"],"executorName":"main","name":"Patch a programsId","startTime":1710990939260,"refId":"[1:11]","endTime":1710990940790,"exampleIndex":-1},{"sectionIndex":1,"stepResults":[{"result":{"nanos":2268512499,"millis":2268.512499,"status":"passed"},"step":{"background":true,"line":4,"prefix":"*","index":0,"text":"call read(\"..\/..\/user\/token\/users-token-post.feature@token\")"},"callResults":[{"failedCount":0,"prefixedPath":"src\/test\/java\/teachers\/patch\/..\/..\/user\/token\/users-token-post.feature","packageQualifiedName":"src.test.java.teachers.patch.user.token.users-token-post","loopIndex":-1,"relativePath":"src\/test\/java\/teachers\/patch\/..\/..\/user\/token\/users-token-post.feature","scenarioResults":[{"sectionIndex":0,"stepResults":[{"result":{"nanos":267400,"millis":0.2674,"status":"passed"},"step":{"line":6,"prefix":"Given","index":0,"text":"url \"https:\/\/funcoeback-dev-ceqh.3.us-1.fl0.io\/users\/token\/\""}},{"result":{"nanos":173900,"millis":0.1739,"status":"passed"},"step":{"line":7,"prefix":"And","index":1,"text":"request {\"user\": \"ruben1\", \"password\": \"ruben123\"}"}},{"result":{"nanos":2230316800,"millis":2230.3168,"status":"passed"},"step":{"line":8,"prefix":"When","index":2,"text":"method post"},"stepLog":"22:15:40.822 request:\n1 > POST https:\/\/funcoeback-dev-ceqh.3.us-1.fl0.io\/users\/token\/\n1 > Content-Type: application\/json; charset=UTF-8\n1 > Content-Length: 39\n1 > Host: funcoeback-dev-ceqh.3.us-1.fl0.io\n1 > Connection: Keep-Alive\n1 > User-Agent: Apache-HttpClient\/4.5.13 (Java\/21.0.2)\n1 > Accept-Encoding: gzip,deflate\n{\"user\":\"ruben1\",\"password\":\"ruben123\"}\n\n22:15:43.050 response time in milliseconds: 2227\n1 < 200\n1 < date: Thu, 21 Mar 2024 03:15:40 GMT\n1 < server: envoy\n1 < content-length: 164\n1 < content-type: application\/json\n1 < x-envoy-upstream-service-time: 1932\n{\"access_token\":\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoicnViZW4xIiwiZXhwaXJlcyI6MTcxMTA5MDk0My40MjY0MTJ9.cCF0FfMtgOagZ1HqaZD2Byvi5K8X2CPvl2GKv6dlqcY\"}\n\n"},{"result":{"nanos":12801,"millis":0.012801,"status":"passed"},"step":{"line":9,"prefix":"Then","index":3,"text":"status 200"}},{"result":{"nanos":20124601,"millis":20.124601,"status":"passed"},"step":{"line":10,"prefix":"*","index":4,"text":"def token = $.access_token"}}],"line":5,"description":"","durationMillis":2250.895502,"failed":false,"tags":["token"],"executorName":"main","name":"Post a token","startTime":1710990940820,"refId":"[1:5]","endTime":1710990943071,"exampleIndex":-1}],"callDepth":1,"name":"JWT Token Feature","description":"","resultDate":"2024-03-20 10:15:46 p.\u202Fm.","durationMillis":2250.895502,"passedCount":1}]},{"result":{"nanos":9872499,"millis":9.872499,"status":"passed"},"step":{"background":true,"line":5,"prefix":"*","index":1,"text":"header Authorization = \"Bearer \" + token"}},{"result":{"nanos":10480600,"millis":10.4806,"status":"passed"},"step":{"background":true,"line":6,"prefix":"*","index":2,"text":"print token"},"stepLog":"22:15:43.092 [print] eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoicnViZW4xIiwiZXhwaXJlcyI6MTcxMTA5MDk0My40MjY0MTJ9.cCF0FfMtgOagZ1HqaZD2Byvi5K8X2CPvl2GKv6dlqcY \n"},{"result":{"nanos":2112591801,"millis":2112.591801,"status":"passed"},"step":{"background":true,"line":7,"prefix":"*","index":3,"text":"call read(\"..\/post\/teacher-post.feature@createteachers\")"},"callResults":[{"failedCount":0,"prefixedPath":"src\/test\/java\/teachers\/patch\/..\/post\/teacher-post.feature","packageQualifiedName":"src.test.java.teachers.patch.post.teacher-post","loopIndex":-1,"relativePath":"src\/test\/java\/teachers\/patch\/..\/post\/teacher-post.feature","scenarioResults":[{"sectionIndex":0,"stepResults":[{"result":{"nanos":1004556000,"millis":1004.556,"status":"passed"},"step":{"background":true,"line":4,"prefix":"*","index":0,"text":"call read(\"..\/..\/user\/token\/users-token-post.feature@token\")"},"callResults":[{"failedCount":0,"prefixedPath":"src\/test\/java\/teachers\/patch\/..\/..\/user\/token\/users-token-post.feature","packageQualifiedName":"src.test.java.teachers.patch.user.token.users-token-post","loopIndex":-1,"relativePath":"src\/test\/java\/teachers\/patch\/..\/..\/user\/token\/users-token-post.feature","scenarioResults":[{"sectionIndex":0,"stepResults":[{"result":{"nanos":177500,"millis":0.1775,"status":"passed"},"step":{"line":6,"prefix":"Given","index":0,"text":"url \"https:\/\/funcoeback-dev-ceqh.3.us-1.fl0.io\/users\/token\/\""}},{"result":{"nanos":110100,"millis":0.1101,"status":"passed"},"step":{"line":7,"prefix":"And","index":1,"text":"request {\"user\": \"ruben1\", \"password\": \"ruben123\"}"}},{"result":{"nanos":998597500,"millis":998.5975,"status":"passed"},"step":{"line":8,"prefix":"When","index":2,"text":"method post"},"stepLog":"22:15:43.111 request:\n2 > POST https:\/\/funcoeback-dev-ceqh.3.us-1.fl0.io\/users\/token\/\n2 > Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoicnViZW4xIiwiZXhwaXJlcyI6MTcxMTA5MDk0My40MjY0MTJ9.cCF0FfMtgOagZ1HqaZD2Byvi5K8X2CPvl2GKv6dlqcY\n2 > Content-Type: application\/json; charset=UTF-8\n2 > Content-Length: 39\n2 > Host: funcoeback-dev-ceqh.3.us-1.fl0.io\n2 > Connection: Keep-Alive\n2 > User-Agent: Apache-HttpClient\/4.5.13 (Java\/21.0.2)\n2 > Accept-Encoding: gzip,deflate\n{\"user\":\"ruben1\",\"password\":\"ruben123\"}\n\n22:15:44.107 response time in milliseconds: 995\n2 < 200\n2 < date: Thu, 21 Mar 2024 03:15:42 GMT\n2 < server: envoy\n2 < content-length: 166\n2 < content-type: application\/json\n2 < x-envoy-upstream-service-time: 725\n{\"access_token\":\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoicnViZW4xIiwiZXhwaXJlcyI6MTcxMTA5MDk0NC40ODM4ODU4fQ.Zf2XwmuZhadWkBzF7cbvHIZJymavNrXpo08Ei9ZZb54\"}\n\n"},{"result":{"nanos":14401,"millis":0.014401,"status":"passed"},"step":{"line":9,"prefix":"Then","index":3,"text":"status 200"}},{"result":{"nanos":710800,"millis":0.7108,"status":"passed"},"step":{"line":10,"prefix":"*","index":4,"text":"def token = $.access_token"}}],"line":5,"description":"","durationMillis":999.610301,"failed":false,"tags":["token"],"executorName":"main","name":"Post a token","startTime":1710990943109,"refId":"[1:5]","endTime":1710990944109,"exampleIndex":-1}],"callDepth":2,"name":"JWT Token Feature","description":"","resultDate":"2024-03-20 10:15:46 p.\u202Fm.","durationMillis":999.610301,"passedCount":1}]},{"result":{"nanos":356400,"millis":0.3564,"status":"passed"},"step":{"background":true,"line":5,"prefix":"*","index":1,"text":"header Authorization = \"Bearer \" + token"}},{"result":{"nanos":454600,"millis":0.4546,"status":"passed"},"step":{"background":true,"line":6,"prefix":"*","index":2,"text":"print token"},"stepLog":"22:15:44.110 [print] eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoicnViZW4xIiwiZXhwaXJlcyI6MTcxMTA5MDk0NC40ODM4ODU4fQ.Zf2XwmuZhadWkBzF7cbvHIZJymavNrXpo08Ei9ZZb54 \n"},{"result":{"nanos":23821201,"millis":23.821201,"status":"passed"},"step":{"line":11,"prefix":"*","index":0,"text":"def randomidcard = \" ' \" + Math.floor(Math.random() * 1000000000000) + 1 + \" ' \""}},{"result":{"nanos":2079300,"millis":2.0793,"status":"passed"},"step":{"line":12,"prefix":"*","index":1,"text":"def randomphone = \" +57 \" + Math.floor(Math.random() * 1000000000) + 1 + \" ' \""}},{"result":{"nanos":26214400,"millis":26.2144,"status":"passed"},"step":{"endLine":24,"line":13,"prefix":"*","docString":"function() {\n    var chars = 'abcdefghijklmnopqrstuvwxyz';\n    var randomMail = '';\n    for (var i = 0; i < 8; i++) {\n        var randomIndex = Math.floor(Math.random() * chars.length);\n        randomMail += chars.charAt(randomIndex);\n    }\n    return randomMail;\n}","index":2,"text":"def generateRandomMail ="}},{"result":{"nanos":9973099,"millis":9.973099,"status":"passed"},"step":{"line":26,"prefix":"*","index":3,"text":"def randomMail = generateRandomMail() + \"@gmail.com\""}},{"result":{"nanos":1142900,"millis":1.1429,"status":"passed"},"step":{"endLine":38,"line":27,"prefix":"*","docString":"function() {\n    var chars = 'abcdefghijklmnopqrstuvwxyz';\n    var randomName = '';\n    for (var i = 0; i < 8; i++) {\n        var randomIndex = Math.floor(Math.random() * chars.length);\n        randomName += chars.charAt(randomIndex);\n    }\n    return randomName;\n}","index":4,"text":"def generateRandomName ="}},{"result":{"nanos":1048200,"millis":1.0482,"status":"passed"},"step":{"line":39,"prefix":"*","index":5,"text":"def randomname = generateRandomName()"}},{"result":{"nanos":1098100,"millis":1.0981,"status":"passed"},"step":{"endLine":52,"line":41,"prefix":"*","docString":"function() {\n    var chars = 'abcdefghijklmnopqrstuvwxyz';\n    var randomlastname = '';\n    for (var i = 0; i < 8; i++) {\n        var randomIndex = Math.floor(Math.random() * chars.length);\n        randomlastname += chars.charAt(randomIndex);\n    }\n    return randomlastname;\n}","index":6,"text":"def generateRandomLastName ="}},{"result":{"nanos":1130700,"millis":1.1307,"status":"passed"},"step":{"line":53,"prefix":"*","index":7,"text":"def randomlastname = generateRandomLastName()"}},{"result":{"nanos":361100,"millis":0.3611,"status":"passed"},"step":{"endLine":65,"line":54,"prefix":"*","docString":"function() {\n    var chars = 'abcdefghijklmnopqrstuvwxyz';\n    var randomName = '';\n    for (var i = 0; i < 8; i++) {\n        var randomIndex = Math.floor(Math.random() * chars.length);\n        randomName += chars.charAt(randomIndex);\n    }\n    return randomName;\n}","index":8,"text":"def generateRandomName ="}},{"result":{"nanos":669000,"millis":0.669,"status":"passed"},"step":{"line":67,"prefix":"*","index":9,"text":"def randomnameuser = generateRandomName()"}},{"result":{"nanos":1125200,"millis":1.1252,"status":"passed"},"step":{"endLine":80,"line":69,"prefix":"*","docString":"function() {\n    var chars = 'abcdefghijklmnopqrstuvwxyz1234567890#$%&\/():;,!';\n    var randomPassword = '';\n    for (var i = 0; i < 10; i++) {\n        var randomIndex = Math.floor(Math.random() * chars.length);\n        randomPassword += chars.charAt(randomIndex);\n    }\n    return randomPassword;\n}","index":10,"text":"def generateRandomPassword ="}},{"result":{"nanos":1361599,"millis":1.361599,"status":"passed"},"step":{"line":81,"prefix":"*","index":11,"text":"def randompassworduser = generateRandomPassword()"}},{"result":{"nanos":367300,"millis":0.3673,"status":"passed"},"step":{"line":82,"prefix":"Given","index":12,"text":"url \"https:\/\/funcoeback-dev-ceqh.3.us-1.fl0.io\/teachers\/\""}},{"result":{"nanos":3455100,"millis":3.4551,"status":"passed"},"step":{"line":83,"prefix":"And","index":13,"text":"request {\"document_type_uuid\": \"09359aab-7354-47c0-ae6b-60d71aea3f08\", \"identification_card\": '#(randomidcard)', \"first_name\": '#(randomname)',  \"last_name\": '#(randomlastname)',  \"blood_type_uuid\": \"6f454a83-4201-44e3-b7cf-99ba07464519\",  \"gender_uuid\": \"20be8f69-c198-467c-89be-ee18a7af8b9b\",  \"phone\": '#(randomphone)',  \"user\": '#(randomnameuser)',  \"password\": '#(randompassworduser)', \"program_uuid\": \"50ae87d2-09de-4a87-aeca-a4236d9a602b\"}"}},{"result":{"nanos":1001204801,"millis":1001.204801,"status":"passed"},"step":{"line":84,"prefix":"When","index":14,"text":"method post"},"stepLog":"22:15:44.186 request:\n3 > POST https:\/\/funcoeback-dev-ceqh.3.us-1.fl0.io\/teachers\/\n3 > Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoicnViZW4xIiwiZXhwaXJlcyI6MTcxMTA5MDk0NC40ODM4ODU4fQ.Zf2XwmuZhadWkBzF7cbvHIZJymavNrXpo08Ei9ZZb54\n3 > Content-Type: application\/json; charset=UTF-8\n3 > Content-Length: 388\n3 > Host: funcoeback-dev-ceqh.3.us-1.fl0.io\n3 > Connection: Keep-Alive\n3 > User-Agent: Apache-HttpClient\/4.5.13 (Java\/21.0.2)\n3 > Accept-Encoding: gzip,deflate\n{\"document_type_uuid\":\"09359aab-7354-47c0-ae6b-60d71aea3f08\",\"identification_card\":\" ' 4727410757781 ' \",\"first_name\":\"cvpflyeq\",\"last_name\":\"tijfvgtb\",\"blood_type_uuid\":\"6f454a83-4201-44e3-b7cf-99ba07464519\",\"gender_uuid\":\"20be8f69-c198-467c-89be-ee18a7af8b9b\",\"phone\":\" +57 9386951181 ' \",\"user\":\"bomnfnxu\",\"password\":\"\\\/qxey!;8y4\",\"program_uuid\":\"50ae87d2-09de-4a87-aeca-a4236d9a602b\"}\n\n22:15:45.185 response time in milliseconds: 999\n3 < 200\n3 < date: Thu, 21 Mar 2024 03:15:43 GMT\n3 < server: envoy\n3 < content-length: 517\n3 < content-type: application\/json\n3 < x-envoy-upstream-service-time: 729\n{\"uuid_teacher\":\"a2672072-08e6-43c8-8ef4-712011de1659\",\"document_type_uuid\":\"09359aab-7354-47c0-ae6b-60d71aea3f08\",\"identification_card\":\" ' 4727410757781 ' \",\"first_name\":\"cvpflyeq\",\"last_name\":\"tijfvgtb\",\"blood_type_uuid\":\"6f454a83-4201-44e3-b7cf-99ba07464519\",\"gender_uuid\":\"20be8f69-c198-467c-89be-ee18a7af8b9b\",\"phone\":\" +57 9386951181 ' \",\"user\":\"bomnfnxu\",\"password\":\"\/qxey!;8y4\",\"created_at\":\"2024-03-21T03:15:45\",\"last_connection\":null,\"program_uuid\":\"50ae87d2-09de-4a87-aeca-a4236d9a602b\",\"updated_at\":null}\n\n"},{"result":{"nanos":12400,"millis":0.0124,"status":"passed"},"step":{"line":85,"prefix":"Then","index":15,"text":"status 200"}},{"result":{"nanos":315501,"millis":0.315501,"status":"passed"},"step":{"line":86,"prefix":"*","index":16,"text":"def teacherId = $.uuid_teacher"}},{"result":{"nanos":910500,"millis":0.9105,"status":"passed"},"step":{"line":87,"prefix":"*","index":17,"text":"print \" se a creado la identificacion del profesor # \" + teacherId"},"stepLog":"22:15:45.187 [print]  se a creado la identificacion del profesor # a2672072-08e6-43c8-8ef4-712011de1659 \n"},{"result":{"nanos":266401,"millis":0.266401,"status":"passed"},"step":{"line":88,"prefix":"*","index":18,"text":"def idcard = $.identification_card"}},{"result":{"nanos":781299,"millis":0.781299,"status":"passed"},"step":{"line":89,"prefix":"*","index":19,"text":"print \" la cedula del profesor es la # \" + idcard"},"stepLog":"22:15:45.188 [print]  la cedula del profesor es la #  ' 4727410757781 '  \n"},{"result":{"nanos":388400,"millis":0.3884,"status":"passed"},"step":{"line":90,"prefix":"*","index":20,"text":"def teacher_name = $.first_name"}},{"result":{"nanos":3288700,"millis":3.2887,"status":"passed"},"step":{"line":91,"prefix":"*","index":21,"text":"def teacher_last_name = $.last_name"}},{"result":{"nanos":946500,"millis":0.9465,"status":"passed"},"step":{"line":92,"prefix":"*","index":22,"text":"print \"el nombre completo del teacher es \" + teacher_name + \" \" + teacher_last_name"},"stepLog":"22:15:45.193 [print] el nombre completo del teacher es cvpflyeq tijfvgtb \n"}],"line":10,"description":"","durationMillis":2087.328701,"failed":false,"tags":["createteachers"],"executorName":"main","name":"Post on teachers","startTime":1710990943105,"refId":"[1:10]","endTime":1710990945193,"exampleIndex":-1}],"callDepth":1,"name":"Post teachers on request","description":"","resultDate":"2024-03-20 10:15:46 p.\u202Fm.","durationMillis":2087.328701,"passedCount":1}]},{"result":{"nanos":480000,"millis":0.48,"status":"passed"},"step":{"line":21,"prefix":"Given","index":0,"text":"url 'https:\/\/funcoeback-dev-ceqh.3.us-1.fl0.io\/teachers\/uuid_teacher?uuid=' + teacherId"}},{"result":{"nanos":628600,"millis":0.6286,"status":"passed"},"step":{"line":22,"prefix":"*","index":1,"text":"print teacherId"},"stepLog":"22:15:45.206 [print] a2672072-08e6-43c8-8ef4-712011de1659 \n"},{"result":{"nanos":246299,"millis":0.246299,"status":"passed"},"step":{"line":23,"prefix":"And","index":2,"text":"request {\"first_name\": '#(randomname)'}"}},{"result":{"nanos":847970100,"millis":847.9701,"status":"passed"},"step":{"line":24,"prefix":"When","index":3,"text":"method patch"},"stepLog":"22:15:45.208 request:\n4 > PATCH https:\/\/funcoeback-dev-ceqh.3.us-1.fl0.io\/teachers\/uuid_teacher?uuid=a2672072-08e6-43c8-8ef4-712011de1659\n4 > Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoicnViZW4xIiwiZXhwaXJlcyI6MTcxMTA5MDk0NC40ODM4ODU4fQ.Zf2XwmuZhadWkBzF7cbvHIZJymavNrXpo08Ei9ZZb54\n4 > Content-Type: application\/json; charset=UTF-8\n4 > Content-Length: 25\n4 > Host: funcoeback-dev-ceqh.3.us-1.fl0.io\n4 > Connection: Keep-Alive\n4 > User-Agent: Apache-HttpClient\/4.5.13 (Java\/21.0.2)\n4 > Accept-Encoding: gzip,deflate\n{\"first_name\":\"cvpflyeq\"}\n\n22:15:46.054 response time in milliseconds: 846\n4 < 200\n4 < date: Thu, 21 Mar 2024 03:15:44 GMT\n4 < server: envoy\n4 < content-length: 534\n4 < content-type: application\/json\n4 < x-envoy-upstream-service-time: 567\n{\"uuid_teacher\":\"a2672072-08e6-43c8-8ef4-712011de1659\",\"document_type_uuid\":\"09359aab-7354-47c0-ae6b-60d71aea3f08\",\"identification_card\":\" ' 4727410757781 ' \",\"first_name\":\"cvpflyeq\",\"last_name\":\"tijfvgtb\",\"blood_type_uuid\":\"6f454a83-4201-44e3-b7cf-99ba07464519\",\"gender_uuid\":\"20be8f69-c198-467c-89be-ee18a7af8b9b\",\"phone\":\" +57 9386951181 ' \",\"user\":\"bomnfnxu\",\"password\":\"\/qxey!;8y4\",\"created_at\":\"2024-03-21T03:15:45\",\"last_connection\":null,\"program_uuid\":\"50ae87d2-09de-4a87-aeca-a4236d9a602b\",\"updated_at\":\"2024-03-21T03:15:45\"}\n\n"},{"result":{"nanos":29599,"millis":0.029599,"status":"passed"},"step":{"line":25,"prefix":"Then","index":4,"text":"status 200"}},{"result":{"nanos":1489301,"millis":1.489301,"status":"passed"},"step":{"line":26,"prefix":"And","index":5,"text":"print \"El Registro Se Actualizo De Forma Exitosa \" + teacherId"},"stepLog":"22:15:46.056 [print] El Registro Se Actualizo De Forma Exitosa a2672072-08e6-43c8-8ef4-712011de1659 \n"},{"result":{"nanos":227700,"millis":0.2277,"status":"passed"},"step":{"line":27,"prefix":"And","index":6,"text":"def responseJson = response"}},{"result":{"nanos":1784299,"millis":1.784299,"status":"passed"},"step":{"line":28,"prefix":"And","index":7,"text":"print responseJson"},"stepLog":"22:15:46.058 [print] {\n  \"uuid_teacher\": \"a2672072-08e6-43c8-8ef4-712011de1659\",\n  \"document_type_uuid\": \"09359aab-7354-47c0-ae6b-60d71aea3f08\",\n  \"identification_card\": \" ' 4727410757781 ' \",\n  \"first_name\": \"cvpflyeq\",\n  \"last_name\": \"tijfvgtb\",\n  \"blood_type_uuid\": \"6f454a83-4201-44e3-b7cf-99ba07464519\",\n  \"gender_uuid\": \"20be8f69-c198-467c-89be-ee18a7af8b9b\",\n  \"phone\": \" +57 9386951181 ' \",\n  \"user\": \"bomnfnxu\",\n  \"password\": \"\/qxey!;8y4\",\n  \"created_at\": \"2024-03-21T03:15:45\",\n  \"last_connection\": null,\n  \"program_uuid\": \"50ae87d2-09de-4a87-aeca-a4236d9a602b\",\n  \"updated_at\": \"2024-03-21T03:15:45\"\n}\n \n"}],"line":20,"description":"","durationMillis":5254.313297,"failed":false,"tags":["updateteachername"],"executorName":"main","name":"Patch a programsId","startTime":1710990940799,"refId":"[2:20]","endTime":1710990946058,"exampleIndex":-1}],"callDepth":0,"name":"Patch programs on request","description":"","resultDate":"2024-03-20 10:15:46 p.\u202Fm.","durationMillis":6755.204597,"passedCount":1}